version: "3.8"

services:

############################# PROXY

  cloudflared:
    container_name: cloudflared_tunnel
    image: cloudflare/cloudflared:latest
    restart: always
    security_opt:
      - no-new-privileges:true
    command: tunnel --no-autoupdate run --token $CLOUDFLARED_TOKEN

############################# SYSTEM

  # Dozzle - Real-time Docker Log Viewer
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - $DOZZLE_PORT:8080
    environment:
#      DOZZLE_LEVEL: info
      DOZZLE_TAILSIZE: 300
#      DOZZLE_FILTER: "status=running"
#      DOZZLE_FILTER: "label=log_me" # limits logs displayed to containers with this label
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
