services:
  adguardhome-sync:
    image: lscr.io/linuxserver/adguardhome-sync:latest
    container_name: adguardhome-sync
    restart: always
    security_opt:
      - no-new-privileges:true
    ports:
      - $ADGUARDHOMESYNC_PORT:8080
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      #- CONFIGFILE=/config/adguardhome-sync.yaml #optional
    volumes:
      - $SERVICES_DIR/adguardhome-sync/config:/config
