version: "3.8"

services:

############################# MEDIA

  # Plex
  # URL to access plex instance: http://<host ip>:$32400/web
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    network_mode: host
    environment:
      PUID: $PUID
      PGID: $PGID
      VERSION: docker
      #UMASK: 022
      #PLEX_CLAIM: #optional: https://www.plex.tv/claim
    volumes:
      - $SERVICES_DIR/plex/config:/config
      - $PLEX_MOVIES_HDD_ONE_DIR:/PlexMoviesAndShows_One
      #- $PLEX_MOVIES_HDD_TWO_DIR:/movies_Hdd_Two
    #devices:
      #- /dev/dri:/dev/dri