version: "3.8"

services:

############################# FILE SYSTEM

  # Syncthing
  # Setup: https://www.addictedtotech.net/installing-syncthing-on-a-raspberry-pi-using-docker-portainer-episode-11/
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: $SYNCTHING_HOSTNAME
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - $SYNCTHING_UI:8384
      - $SYNCTHING_TCP:22000/tcp
      - $SYNCTHING_UDP:22000/udp
      - $SYNCTHING_UDP_DISCOVERY:21027/udp
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $SERVICES_DIR/syncthing/config:/config # In-app, change default folder to /config/Sync under Actions >> Settings >> Edit folder defaults
      - $SYNCTHING_DATA1:/SyncData1
      #- /path/to/data2:/data2