version: "3.9"

services:

############################# NETWORK

  # Transmission OpenVPN
  transmission_openvpn:
    image: haugene/transmission-openvpn:3.0.2-armhf #latest-armhf / 2.13-armhf / 3.0.2-armhf
    container_name: transmission_openvpn
    restart: unless-stopped # If not always, disable WEBPROXY_ENABLED
    cap_add:
      - NET_ADMIN
    dns:
      #- 8.8.8.8
      #- 8.8.4.4
      - $DNS_RESOLVER
    ports:
      - $TRANSMISSIONOPENVPN_GUI_PORT:9091 # GUI
      - $TRANSMISSIONOPENVPN_PORT:8888 # Transmission Port
    devices:
      - /dev/net/tun # This creates a tunnel for Transmission
    volumes:
      - $SERVICES_DIR/transmissionopenvpn:/config
      - $DOWNLOADS_DIR/torrent:/data # Downloads
      - /etc/localtime:/etc/localtime:ro
    environment:
      # Vpn setup
      - CREATE_TUN_DEVICE=true
      - OPENVPN_PROVIDER=$TRANSMISSIONOPENVPN_PROVIDER
      # - OPENVPN_CONFIG=$TRANSMISSIONOPENVPN_CONFIG_FILES # OpenVpn config file names. Can be comma separated
      - OPENVPN_USERNAME=$TRANSMISSIONOPENVPN_USERNAME
      - OPENVPN_PASSWORD=$TRANSMISSIONOPENVPN_PASSWORD
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60 # Restart if connection fails
      - NORDVPN_COUNTRY=$TRANSMISSIONOPENVPN_NORDVPN_COUNTRY
      - NORDVPN_CATEGORY=$TRANSMISSIONOPENVPN_NORDVPN_CATEGORY
      - NORDVPN_PROTOCOL=$TRANSMISSIONOPENVPN_NORDVPN_PROTOCOL
      # Local network
      - LOCAL_NETWORK=$TRANSMISSIONOPENVPN_LOCAL_NETWORK # Match the local network of the host device
      - PUID=$PUID
      - PGID=$PGID
      # Proxy
      - WEBPROXY_ENABLED=false # Enable other containers to use the vpn
      - WEBPROXY_PORT=$TRANSMISSIONOPENVPN_PORT
      # Connections
      - TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false
      - TRANSMISSION_PEER_LIMIT_GLOBAL=1500
      - TRANSMISSION_MAX_PEERS_GLOBAL=1500
      - TRANSMISSION_PEER_LIMIT_PER_TORRENT=50
      - TRANSMISSION_UPLOAD_SLOTS_PER_TORRENT=5
      - TRANSMISSION_DOWNLOAD_QUEUE_ENABLED=true
      - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=30
      - TRANSMISSION_IDLE_SEEDING_LIM=5
      - TRANSMISSION_IDLE_SEEDING_LIMIT=5
      - TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED=true
      # Files
      # - TRANSMISSION_PREALLOCATION=1
      # Speed
      - TRANSMISSION_RATIO_LIMIT=2
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - TRANSMISSION_SPEED_LIMIT_UP=30
      - TRANSMISSION_SPEED_LIMIT_UP_ENABLED=true
    logging:
      driver: json-file
      options:
        max-size: 10m
