version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce:latest # Before was 2.17.1
    container_name: portainer
    restart: always
    security_opt:
      - no-new-privileges:true
    ports:
      - $PORTAINER_UI_HTTPS_PORT:9443
      - $PORTAINER_AGENT_PORT:8000
      - $PORTAINER_UI_HTTP_PORT:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $SERVICES_DIR/portainer/data:/data
      - $SERVICES_DIR/portainer/certs:/certs
    #command: >
    #  --sslcert /certs/portainer.crt
    #  --sslkey /certs/portainer.key
