version: "3.9"

services:

############################# WORDPRESS SITE TWO

  # MariaDB
  wp_sitetwo_mariadb:
    container_name: wp_sitetwo_mariadb
    image: linuxserver/mariadb:latest
    restart: always
    security_opt:
      - no-new-privileges:true
    ports:
      - $WP_SITETWO_MARIADB_PORT:3306
    volumes:
      - $WP_SITETWO_DIR/mariadb/data:/config
      - $WP_SITETWO_DIR/mariadb/mysql:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - MYSQL_DATABASE=$WP_SITETWO_DB_NAME
      - MYSQL_ROOT_PASSWORD=$WP_SITETWO_DB_ROOT_PASSWORD
      - MYSQL_USER=$WP_SITETWO_DB_USER
      - MYSQL_PASSWORD=$WP_SITETWO_DB_PASSWORD
    
  # WordPress
    # Create file (volumes) php.conf.uploads.ini and paste below content before container creation:
      #file_uploads = On
      #memory_limit = 64M
      #upload_max_filesize = 64M
      #post_max_size = 64M
      #max_execution_time = 600
  wp_sitetwo_wordpress:
    container_name: wp_sitetwo_wordpress
    image: wordpress:latest
    restart: always
    security_opt:
      - no-new-privileges:true
    ports:
      - $WP_SITETWO_WORDPRESS_PORT:80
    links:
      - wp_sitetwo_mariadb
    volumes:
      - $WP_SITETWO_DIR/www/config/php.conf.uploads.ini:/usr/local/etc/php/conf.d/uploads.ini # Create file in advance
      - $WP_SITETWO_DIR/www/wp-app:/var/www/html
    environment:
      WORDPRESS_DB_HOST: wp_sitetwo_mariadb
      WORDPRESS_DB_NAME: $WP_SITETWO_DB_NAME
      WORDPRESS_DB_USER: $WP_SITETWO_DB_USER
      WORDPRESS_DB_PASSWORD: $WP_SITETWO_DB_PASSWORD