version: "3.8"

networks:
  traefik2_proxy:
    external:
      name: traefik2_proxy

services:

  # Traefik v2
  traefik2:
    image: traefik:chevrotin # chevrotin tag refers to v2.2.x
    container_name: traefik2
    restart: always
    networks:
      - traefik2_proxy
    ports:
      - 80:80
      - 443:443
    command:
      # General
      - --global.checkNewVersion=true
      - --global.sendAnonymousUsage=false
      # Log
      - --log=true
      - --log.level=DEBUG
      - --accessLog=true
      - --accessLog.filePath=/traefik.log
      - --accessLog.bufferingSize=100 # Configuring a buffer of 100 lines
      # Api
      - --api.dashboard=true
      # Entry Points
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      # Providers
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=traefik2_proxy
      - --providers.docker.swarmMode=false
      - --providers.file.directory=/rules # Load dynamic configuration from one or more .toml or .yml files in a directory.
      - --providers.file.watch=true # Only works on top level files in the rules folder
      # Lets Encrypt Http Challenge
#      - --certificatesresolvers.letsencrypt.acme.httpchallenge=true
#      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
      # Lets Encrypt Tls Challenge (might need comment all references to port 80 and entrypoint.web)
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      # Lets Encrypt General Config
#      - --certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory # Only for testing
      - --certificatesresolvers.letsencrypt.acme.email=$MY_EMAIL
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json # File must have chmod 600
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "$DOCKERDIR/traefik2/rules:/rules"
      - "$DOCKERDIR/traefik2/letsencrypt:/letsencrypt"
      - "$DOCKERDIR/traefik2/traefik.log:/traefik.log"
    labels:
      - "traefik.enable=true"
      # Router
      - "traefik.http.routers.traefik-rtr.rule=Host(`traefik.$DOMAINNAME`)"
      - "traefik.http.routers.traefik-rtr.entrypoints=websecure"
#      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik-rtr.tls.certresolver=letsencrypt"
      # Middlewares
#      - "traefik.http.routers.traefik-rtr.middlewares=chain-oauth@file"
      # Service
      - "traefik.http.routers.traefik-rtr.service=api@internal"
      # Domains
      - "traefik.http.routers.traefik-rtr.tls.domains[0].main=$DOMAINNAME"
      - "traefik.http.routers.traefik-rtr.tls.domains[0].sans=*.$DOMAINNAME"
      - "traefik.http.routers.traefik-rtr.tls.domains[1].main=$DOMAINNAME_BLOG"
      - "traefik.http.routers.traefik-rtr.tls.domains[1].sans=*.$DOMAINNAME_BLOG"
      # Http to Https Redirect
      - "traefik.http.routers.http-catchall-rtr.rule=hostregexp(`{any:.+}`)"
      - "traefik.http.routers.http-catchall-rtr.entrypoints=web"
      - "traefik.http.routers.http-catchall-rtr.middlewares=redirect-to-https-mdl@docker"
      - "traefik.http.middlewares.redirect-to-https-mdl.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https-mdl.redirectscheme.permanent=true"

  # Google OAuth - Single Sign On using OAuth 2.0 for Traefik 2.2
  # https://console.developers.google.com/
  oauth:
    container_name: oauth
    # image: thomseddon/traefik-forward-auth:latest
    image: thomseddon/traefik-forward-auth:2.1-arm # Use this image with Raspberry Pi
    restart: always
    networks:
      - traefik2_proxy
    security_opt:
      - no-new-privileges:true
    environment:
      - CLIENT_ID=$GOOGLE_CLIENT_ID
      - CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
      - SECRET=$OAUTH_SECRET
      - COOKIE_DOMAIN=$DOMAINNAME
      - INSECURE_COOKIE=false
      - AUTH_HOST=oauth.$DOMAINNAME
      - URL_PATH=/_oauth # must match url defined in google web application
      - WHITELIST=$OAUTH_EMAIL_1,$OAUTH_EMAIL_2,$OAUTH_EMAIL_3 # email1,email2,email3 or $EMAIL1,$EMAIL2,$EMAIL3
      - LOG_LEVEL=info
      - LOG_FORMAT=text
      - LIFETIME=$OAUTH_SESSION_LIFETIME
      - DEFAULT_ACTION=auth
      - DEFAULT_PROVIDER=google
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.oauth-rtr.rule=Host(`oauth.$DOMAINNAME`)"
      - "traefik.http.routers.oauth-rtr.entrypoints=websecure"
      - "traefik.http.routers.oauth-rtr.tls.certresolver=letsencrypt"
      ## Middlewares
      - "traefik.http.routers.oauth-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.oauth-rtr.service=oauth-svc"
      - "traefik.http.services.oauth-svc.loadbalancer.server.port=4181"