networks:
  adguardhome_macvlan:
    name: adguardhome_macvlan
    driver: macvlan
    enable_ipv6: false
    driver_opts:
      parent: eth0 # using ifconfig
    ipam:
      config:
        - subnet: $DOCKERVLAN_SUBNET
          ip_range: $ADGUARDHOME_IPV4_ADDRESS/32
          gateway: $DOCKERVLAN_GATEWAY

  adguardhome_vlan_bridge:
    name: adguardhome_vlan_bridge
    driver: bridge
    enable_ipv6: false
    ipam:
      config:
        - subnet: $DOCKERVLAN_BRIDGE_SUBNET
          ip_range: $ADGUARDHOME_IPV4_BRIDGE_ADDRESS/32
          gateway: $DOCKERVLAN_BRIDGE_GATEWAY

services:

############################# NETWORK

  # AdGuard Home - DNS AdBlocking
  # https://samuelsson.dev/install-adguard-home-with-docker-on-a-raspberry-pi-4/
  # https://www.smarthomebeginner.com/adguard-home-docker-compose-guide/
  #   Run to create bridge between host and macvlan, and run on every OS reboot/restart, change ip addresses as needed:
  #     First ip is the ip of the bridge, second ip is the ip of the DOCKERVLAN_IP_RANGE variable
  #       sudo ip link add aghbridge link eth0 type macvlan mode bridge && sudo ip addr add 192.168.20.41/32 dev aghbridge && sudo ip link set aghbridge up && sudo ip route add 192.168.20.40/32 dev aghbridge
  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome
    security_opt:
      - no-new-privileges:true
    restart: always
    # profiles: ["core", "all"]
    networks:
      adguardhome_macvlan:
        ipv4_address: $ADGUARDHOME_IPV4_ADDRESS
      adguardhome_vlan_bridge:
        ipv4_address: $ADGUARDHOME_IPV4_BRIDGE_ADDRESS
    ports:
      # Plain DNS
      - 53/tcp
      - 53/udp
      # Admin Panel and DNS-over-HTTPS
      - 80/tcp
      - 443/tcp
      - 443/udp
      - 3000/tcp
      # DNS-over-TLS
      - 853/tcp
      # DNS-over-QUIC
      - 784:784/udp
      - 853:853/udp
      #- 8853:8853/udp
      # DNSCrypt
      - 5443:5443/tcp
      - 5443:5443/udp
      # DHCP Server
      - 67/udp
      - 68/tcp
      - 68/udp
    volumes:
      - $SERVICES_DIR/adguard/conf:/opt/adguardhome/conf 
      - $SERVICES_DIR/adguard/work:/opt/adguardhome/work 
      #- $DOCKERDIR/shared/certs/$DOMAINNAME_HOME_SYNOLOGY:/certs