version: "3.8"

services:

############################# PROXY

  cloudflared:
    container_name: cloudflared_tunnel
    image: cloudflare/cloudflared:latest
    restart: always
    security_opt:
      - no-new-privileges:true
    command: tunnel --no-autoupdate run --token $CLOUDFLARED_TOKEN
