version: "3.9"

networks:
  adguardhome_macvlan:
    name: adguardhome_macvlan
    driver: macvlan
    #enable_ipv6: false
    driver_opts:
      parent: eth0 # using ifconfig
    ipam:
      config:
        - subnet: $DOCKERVLAN_SUBNET
          ip_range: $DOCKERVLAN_IP_RANGE
          gateway: $DOCKERVLAN_GATEWAY

#  vlan_bridge:
#    name: docker_vlan_bridge
#    driver: bridge
#    enable_ipv6: false
#    ipam:
#      config:
#        - subnet: $DOCKERVLAN_BRIDGE_SUBNET
#          ip_range: $DOCKERVLAN_BRIDGE_IP_RANGE
#          gateway: $DOCKERVLAN_BRIDGE_GATEWAY

services:

############################# NETWORK

  # AdGuard Home - DNS AdBlocking
  # https://samuelsson.dev/install-adguard-home-with-docker-on-a-raspberry-pi-4/
  # https://www.smarthomebeginner.com/adguard-home-docker-compose-guide/
  #   Run to create bridge between host and macvlan, and run on every OS reboot/restart, change ip addresses as needed:
  #     First ip is the ip of the bridge, second ip is the ip of the DOCKERVLAN_IP_RANGE variable
  #       sudo ip link add aghbridge link eth0 type macvlan mode bridge && sudo ip addr add 192.168.20.41/32 dev aghbridge && sudo ip link set aghbridge up && sudo ip route add 192.168.20.40/32 dev aghbridge
  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome
    security_opt:
      - no-new-privileges:true
    restart: always
    # profiles: ["core", "all"]
    networks:
      adguardhome_macvlan:
        ipv4_address: $ADGUARDHOME_IPV4_ADDRESS
      #vlan_bridge:
      #  ipv4_address: $ADGUARDHOME_IPV4_BRIDGE_ADDRESS
    ports:
      - 53/udp 
      - 67/udp 
      - 68/tcp 
      - 68/udp 
      - 80/tcp 
      - 443/tcp 
      - 853/tcp 
      - 3000/tcp 
    volumes:
      - $SERVICES_DIR/adguard/conf:/opt/adguardhome/conf 
      - $SERVICES_DIR/adguard/work:/opt/adguardhome/work 
      #- $DOCKERDIR/shared/certs/$DOMAINNAME_HOME_SYNOLOGY:/certs