version: "3.8"

services:

############################# SYSTEM

  # Dozzle - Real-time Docker Log Viewer
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - $DOZZLE_PORT:8080
    environment:
      #DOZZLE_LEVEL: info
      DOZZLE_TAILSIZE: 300
      #DOZZLE_FILTER: "status=running"
      #DOZZLE_FILTER: "label=log_me" # limits logs displayed to containers with this label
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

############################# NETWORK

  # WireGuard Easy Server
  wireguardg_easy:
    container_name: wireguard_easy
    image: weejewel/wg-easy:latest
    hostname: wireguard_easy
    security_opt:
      - no-new-privileges:true
    ports:
      - $WIREGUARD_UDP_PORT:51820/udp # WireGuard
      - $WIREGUARD_TCP_PORT:51821/tcp # UI
    restart: always
    environment:
      - WG_HOST=$WIREGUARD_HOST # wg server
      - PASSWORD=$WIREGUARD_UI_PASSWORD # UI password
      - WG_PERSISTENT_KEEPALIVE=$WIREGUARD_KEEPALIVE
      - WG_DEFAULT_DNS=$WIREGUARD_DNS
    volumes:
      - $SERVICES_DIR/wireguard_easy:/etc/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=$WIREGUARD_IP_FORWARD
      - net.ipv4.conf.all.src_valid_mark=$WIREGUARD_ALL_SRV_VALID

#  firefox:
#    image: linuxserver/firefox:latest
#    container_name: firefox
#    restart: unless-stopped
#    ports:
#      - $FIREFOX_PORT:3000
#    security_opt:
#      - no-new-privileges:true
#    environment:
#      - PUID=$PUID
#      - PGID=$PGID
#      - TZ=$TZ
#    volumes:
#      - $SERVICES_DIR/firefox/config:/config
#    shm_size: $FIREFOX_SHM_SIZE
