version: "3.8"

networks:
  ngproxy:
    external:
      name: ngproxy
  database:
    external:
      name: database
  myvpn:
    external:
      name: myvpn

services:

############################# PROXY

  # Cloudflare tunnel: main site
  cloudflared:
    container_name: cloudflared_services
    image: cloudflare/cloudflared:latest
    networks:
      - ngproxy
    restart: always
    security_opt:
      - no-new-privileges:true
    command: tunnel --no-autoupdate run --token $CLOUDFLARED_TOKEN_MAIN

############################# SYSTEM

  # Dozzle - Real-time Docker Log Viewer
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    networks:
      - ngproxy
    security_opt:
      - no-new-privileges:true
    ports:
      - "$DOZZLE_PORT:8080"
    environment:
#      DOZZLE_LEVEL: info
      DOZZLE_TAILSIZE: 300
#      DOZZLE_FILTER: "status=running"
#      DOZZLE_FILTER: "label=log_me" # limits logs displayed to containers with this label
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

############################# DASHBOARD

  # Heimdall Web - Unified Frontend Dashboard
  heimdall:
    container_name: heimdall
    image: linuxserver/heimdall:latest
    restart: unless-stopped
    networks:
      - ngproxy
    security_opt:
      - no-new-privileges:true
    ports:
      - "$HEIMDALL_PORT:80"
    volumes:
      - $SERVICESDIR/heimdall:/config
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
