version: "3.9"

services:

############################# SYSTEM

  # Dozzle - Real-time Docker Log Viewer
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - $DOZZLE_PORT:8080
    environment:
#      DOZZLE_LEVEL: info
      DOZZLE_TAILSIZE: 300
#      DOZZLE_FILTER: "status=running"
#      DOZZLE_FILTER: "label=log_me" # limits logs displayed to containers with this label
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

############################# NETWORK

  # DuckDNS
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    restart: always
    #network_mode: host #optional
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - SUBDOMAINS=$DUCKDNS_SUBDOMAINS
      - TOKEN=$DUCKDNS_TOKEN
      - UPDATE_IP=$DUCKDNS_UPDATE_IP
      - LOG_FILE=true
    volumes:
      - $SERVICES_DIR/duckdns/config:/config

  # WireGuard Easy Server
  # On config files, ensure port matches the one set on WIREGUARD_UDP_PORT
  wireguardg_easy:
    container_name: wireguard_easy
    image: weejewel/wg-easy:latest
    hostname: wireguard_easy
    security_opt:
      - no-new-privileges:true
    ports:
      - $WIREGUARD_UDP_PORT:51820/udp # WireGuard
      - $WIREGUARD_TCP_PORT:51821/tcp # UI
    restart: always
    environment:
      - WG_HOST=$WIREGUARD_HOST # wg server
      - PASSWORD=$WIREGUARD_UI_PASSWORD # UI password
      - WG_PERSISTENT_KEEPALIVE=$WIREGUARD_KEEPALIVE
      - WG_DEFAULT_DNS=$DNS_RESOLVER
    volumes:
      - $SERVICES_DIR/wireguard_easy:/etc/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=$WIREGUARD_IP_FORWARD
      - net.ipv4.conf.all.src_valid_mark=$WIREGUARD_ALL_SRV_VALID

############################# MONITORING

  #uptime_kuma:
  #  container_name: uptime_kuma
  #  image: louislam/uptime-kuma
  #  restart: unless-stopped
  #  ports:
  #    - $UPTIMEKUMA_PORT:3001
  #  security_opt:
  #    - no-new-privileges:true
  #  volumes:
  #    - $SERVICES_DIR/uptime_kuma:/app/data

############################# DASHBOARD

  # Dashy
  dashy:
    container_name: dashy
    image: lissy93/dashy:latest # arm64v8
    ports:
      - $DASHY_PORT:80
    restart: always
    environment:
      - NODE_ENV=$DASHY_NODE_ENV
      - UID=$PUID
      - GID=$PGID
    volumes:
      - $SERVICES_DIR/dashy/config.yml:/app/public/conf.yml # Create file in advance / mkdir dashy / touch config.yml
    #healthcheck:
      #test: ['CMD', 'node', '/app/services/healthcheck']
      #interval: 1m30s
      #timeout: 10s
      #retries: 3
      #start_period: 40s

############################# DEMO SITE

  ## MariaDB
  #wp_demo_mariadb:
  #  container_name: wp_demo_mariadb
  #  image: linuxserver/mariadb:latest
  #  restart: always
  #  security_opt:
  #    - no-new-privileges:true
  #  ports:
  #    - $WP_DEMO_MARIADB_PORT:3306
  #  volumes:
  #    - $WP_DEMO_DIR/mariadb/data:/config
  #    - $WP_DEMO_DIR/mariadb/mysql:/var/lib/mysql
  #    - /etc/timezone:/etc/timezone:ro
  #    - /etc/localtime:/etc/localtime:ro
  #  environment:
  #    - PUID=$PUID
  #    - PGID=$PGID
  #    - MYSQL_ROOT_PASSWORD=$WP_DEMO_DB_ROOT_PASSWORD
  #    - MYSQL_DATABASE=$WP_DEMO_DB_NAME
  #    - MYSQL_USER=$WP_DEMO_DB_USER
  #    - MYSQL_PASSWORD=$WP_DEMO_DB_PASSWORD

  ## WordPress
  #  # Create file (volumes) php.conf.uploads.ini and paste below content before container creation:
  #    #file_uploads = On
  #    #memory_limit = 64M
  #    #upload_max_filesize = 64M
  #    #post_max_size = 64M
  #    #max_execution_time = 600
  #wp_demo_wordpress:
  #  container_name: wp_demo_wordpress
  #  image: wordpress:latest
  #  restart: always
  #  ports:
  #    - $WP_DEMO_WORDPRESS_PORT:80
  #  security_opt:
  #    - no-new-privileges:true
  #  links:
  #    - wp_demo_mariadb
  #  volumes:
  #    - $WP_DEMO_DIR/www/config/php.conf.uploads.ini:/usr/local/etc/php/conf.d/uploads.ini # Create file in advance
  #    - $WP_DEMO_DIR/www/wp-app:/var/www/html # Full wordpress project
  #  environment:
  #    WORDPRESS_DB_HOST: wp_demo_mariadb
  #    WORDPRESS_DB_NAME: $WP_DEMO_DB_NAME
  #    WORDPRESS_DB_USER: $WP_DEMO_DB_USER
  #    WORDPRESS_DB_PASSWORD: $WP_DEMO_DB_PASSWORD

############################# PRODUCTIVITY

  # Visual Code Server
  visualcode_server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: visualcode_server
    ports:
      - $VISUALCODE_SERVER_PORT:8443
    restart: unless-stopped
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      #- PASSWORD=password #optional
      #- HASHED_PASSWORD= #optional
      #- SUDO_PASSWORD=password #optional
      #- SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=$VISUALCODE_SERVER_PROXY_DOMAIN
      - DEFAULT_WORKSPACE=/config/workspace
    volumes:
      - $SERVICES_DIR/visualcode_server/config:/config
