version: "3.8"

networks:
  t2proxy:
    external:
      name: t2proxy
  database:
    external:
      name: database

services:

  # MariaDB
  myownsite_mariadb:
    container_name: myownsite_mariadb
    image: linuxserver/mariadb:latest
    restart: always
    networks:
      - database
    security_opt:
      - no-new-privileges:true
    ports:
      - "$MYOWNSITE_MARIADB_PORT:3306"
    volumes:
      - $MYOWNSITEDIR/myownsite_mariadb/data:/config
      - $MYOWNSITEDIR/myownsite_mariadb/mysql:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - MYSQL_ROOT_PASSWORD=$MARIADB_ROOT_PASSWORD
      - MYSQL_DATABASE=$WORDPRESS_DB_NAME
      - MYSQL_USER=$WORDPRESS_DB_USER
      - MYSQL_PASSWORD=$WORDPRESS_DB_PASSWORD

  # WordPress

  # Create file (volumes) php.conf.uploads.ini and paste below content before container creation:
  #file_uploads = On
  #memory_limit = 64M
  #upload_max_filesize = 64M
  #post_max_size = 64M
  #max_execution_time = 600

  myownsite_wordpress:
    container_name: myownsite_wordpress
    image: wordpress:5.5
    restart: always
    networks:
      - database
      - t2proxy
    security_opt:
      - no-new-privileges:true
    ports:
      - $MYOWNSITE_WORDPRESS_PORT:80
    links:
      - myownsite_mariadb
    volumes:
#      - $MYOWNSITEDIR/myownsite_wordpress/config/php.conf.uploads.ini:/usr/local/etc/php/conf.d/uploads.ini # Create file in advance
      - $MYOWNSITEDIR/myownsite_wordpress/wp-app:/var/www/html # Full wordpress project
    environment:
      WORDPRESS_DB_HOST: myownsite_mariadb
      WORDPRESS_DB_NAME: $WORDPRESS_DB_NAME
      WORDPRESS_DB_USER: $WORDPRESS_DB_USER
      WORDPRESS_DB_PASSWORD: $WORDPRESS_DB_PASSWORD
    labels:
      - "traefik.enable=true"
      # Router
      - "traefik.http.routers.myownsite_wordpress-rtr.rule=Host(`$DOMAINNAME`,`www.$DOMAINNAME`)"
      - "traefik.http.routers.myownsite_wordpress-rtr.entrypoints=websecure"
#      - "traefik.http.routers.myownsite_wordpress-rtr.tls=true"
      - "traefik.http.routers.myownsite_wordpress-rtr.tls.certresolver=letsencrypt"
      # Middleware
      - "traefik.http.routers.myownsite_wordpress-rtr.middlewares=chain-no-auth@file"
      # Service
      - "traefik.http.routers.myownsite_wordpress-rtr.service=myownsite_wordpress-svc"
      - "traefik.http.services.myownsite_wordpress-svc.loadbalancer.server.port=80"
