version: "3.8"

networks:
  t2proxy:
    external:
      name: t2proxy
  database:
    external:
      name: database

services:

  # MariaDB
  blog_mariadb:
    container_name: blog_mariadb
    image: linuxserver/mariadb:latest
    restart: always
    networks:
      - database
    security_opt:
      - no-new-privileges:true
    ports:
      - "$BLOG_MARIADB_PORT:3306"
    volumes:
      - $BLOGDIR/blog_mariadb/data:/config
      - $BLOGDIR/blog_mariadb/mysql:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - MYSQL_ROOT_PASSWORD=$MARIADB_BLOG_ROOT_PASSWORD
      - MYSQL_DATABASE=$WORDPRESS_BLOG_DB_NAME
      - MYSQL_USER=$WORDPRESS_BLOG_DB_USER
      - MYSQL_PASSWORD=$WORDPRESS_BLOG_DB_PASSWORD

  # WordPress
    # Create file (volumes) php.conf.uploads.ini and paste below content before container creation:
    #file_uploads = On
    #memory_limit = 64M
    #upload_max_filesize = 64M
    #post_max_size = 64M
    #max_execution_time = 600
  blog_wordpress:
    container_name: blog_wordpress
    image: wordpress:5.5
    restart: always
    ports:
      - $BLOG_WORDPRESS_PORT:80
    networks:
      - database
      - t2proxy
    security_opt:
      - no-new-privileges:true
    links:
      - blog_mariadb
    volumes:
#      - $BLOGDIR/blog_wordpress/config/php.conf.uploads.ini:/usr/local/etc/php/conf.d/uploads.ini # Create file in advance
      - $BLOGDIR/blog_wordpress/wp-app:/var/www/html # Full wordpress project
    environment:
      WORDPRESS_DB_HOST: blog_mariadb
      WORDPRESS_DB_NAME: $WORDPRESS_BLOG_DB_NAME
      WORDPRESS_DB_USER: $WORDPRESS_BLOG_DB_USER
      WORDPRESS_DB_PASSWORD: $WORDPRESS_BLOG_DB_PASSWORD
    labels:
      - "traefik.enable=true"
      # Router
      - "traefik.http.routers.blog_wordpress-rtr.rule=Host(`$DOMAINNAME_BLOG`,`www.$DOMAINNAME_BLOG`)"
      - "traefik.http.routers.blog_wordpress-rtr.entrypoints=websecure"
#      - "traefik.http.routers.blog_wordpress-rtr.tls=true"
      - "traefik.http.routers.blog_wordpress-rtr.tls.certresolver=letsencrypt"
      # Middleware
      - "traefik.http.routers.blog_wordpress-rtr.middlewares=chain-no-auth@file"
      # Service
      - "traefik.http.routers.blog_wordpress-rtr.service=blog_wordpress-svc"
      - "traefik.http.services.blog_wordpress-svc.loadbalancer.server.port=80"